sonar.projectKey=itext7
sonar.projectName=itext7
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.sources=src
sonar.scm.provider=git
sonar.scm.disabled=true
sonar.projectKey=BogdanKoval4uk_PRACTIkkkk_cb1efefc-8866-47dd-bc60-69336c58ba8f
